( := \left(
[ := \left[
{ := \left\lbrace
(: := \left\lang
{: := \left.
|: := \left\lvert
) := \right)
] := \right]
} := \right\rbrace
:) := \right\rang
:} := \right.
:| := \right\rvert
max := \max
min := \min
sin := \sin
cos := \cos
tg := \tg
sec := \sec
csc := \csc
ctg := \ctg
asin := \arcsin
acos := \arccos
atg := \arctg
actg := \arcctg
sinh := \sinh
cosh := \cosh
tgh := \tanh
ctgh := \coth
exp  := \exp
ln := \ln
lg := \lg
sqrt := \sqrt
del := \partial
grad := \nabla
not := \neg
hat  := \hat
bar := \bar
ul := \underline
vec := \vec
tilde := \tilde
dot := \dot
ddot := \ddot
ubrace := \underbrace
obrace := \overbrace
cancel := \cancel
log := \log
gcd := \gcd
lcm := \m
overset := \overset
underset := \underset
color := \textcolor
mod := \mod
* := \cdot
// := /
setminus := \setminus
xx := \times
@ := \circ
o+ := \oplus
^^ := \land
vv := \lor
nn := \cap
uu := \cup
+- := \pm
-+ := \mp
!= := \ne
<= := \le
>= := \ge
<< := \ll
>> := \gg
in := \in
!in := \notin
sub := \sub
sup := \supset
sube := \sube
supe := \sube
== := \equiv
~~ := \approx
=> := \rArr
<=> := \hArr
alpha := \alpha
beta := \beta
gamma := \gamma
delta := \delta
epsilon := \epsilon
varepsilon := \varepsilon
zeta := \zeta
eta := \eta
theta := \theta
vartheta := \vartheta
iota := \iota
kappa := \kappa
lambda := \lambda
mu := \mu
nu := \nu
xi := \xi
pi := \pi
rho := \rho
sigma := \sigma
tau := \tau
upsilon := \upsilon
phi := \phi
varphi := \varphi
chi := \chi
psi := \psi
omega := \omega
Gamma := \Gamma
Delta := \Delta
Theta := \Theta
Lambda := \Lambda
Xi := \Xi
Pi := \Pi
Sigma := \Sigma
Phi := \Phi
Psi := \Psi
Omega := \Omega
-: := \div
sum := \sum
prod := \prod
^^^ := \bigwedge
vvv := \bigvee
nnn := \bigcap
uuu := \bigcup
lim := \lim
int := \int
oint := \oint
O/ := \empty
oo := \infty
aleph := \alef
:. := \therefore
... := \dots
cdots := \cdots
vdots := \vdots
ddots := \ddots
quad := \quad
/_ := \angle
frown := \frown
/_\ := \triangle
square := \square
CC := \cnums
NN := \N
QQ := \Bbb{Q}
RR := \R
ZZ := \Z
AA := \forall
EE := \exist
uarr := \uarr
darr := \darr
rarr := \rarr
larr := \larr
rArr := \rArr
lArr := \lArr
-> := \rarr
: := \colon
:' := \because
