[left_bracket]
(
[
{
(:
{:
|:
[right_bracket]
)
]
}
:)
:}
:|
[delimiter]
;
,
[font]
bb
bbb
cc
tt
ft
sf
[function.bracket]
max
min
[function.1]
sin
cos
tg
sec
csc
ctg
asin
acos
atg
actg
sinh
cosh
tgh
sech
csch
ctgh
[function.1]
exp
ln
lg
[function.1]
abs
floor
ceil
norm
[function.1]
sqrt
[function.1]
del
grad
not
[function.1]
hat
bar
ul
vec
tilde
dot
ddot
ubrace
obrace
cancel
[function.2]
log
gcd
lcm
root
[function.2]
overset
underset
color
[operator]
mod
+
-
*
//
/
setminus
xx
@
o+
ox
o.
^^
vv
nn
uu
+-
-+
prop
[operator]
=
!=
<
>
<=
>=
<<
>>
in
!in
sub
sup
sube
supe
==
~~
[operator]
=>
<=>
[subsup]
^
_
[symbol]
alpha
beta
gamma
delta
epsilon
varepsilon
zeta
eta
theta
vartheta
iota
kappa
lambda
mu
nu
xi
pi
rho
sigma
tau
upsilon
phi
varphi
chi
psi
omega
Gamma
Delta
Theta
Lambda
Xi
Pi
Sigma
Phi
Psi
Omega
[symbol]
-:
sum
prod
^^^
vvv
nnn
uuu
lim
int
oint
O/
oo
aleph
:.
...
cdots
vdots
ddots
quad
/_
frown
/_\
square
CC
NN
QQ
RR
ZZ
AA
EE
bot
[symbol]
uarr
darr
rarr
larr
rArr
lArr
->
:
:'
'
